// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerstaMain.Data;

#nullable disable

namespace VerstaMain.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250308103445_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VerstaMain.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset>("OrderPickupTime")
                        .HasColumnType("datetime");

                    b.Property<float>("OrderWeight")
                        .HasColumnType("float");

                    b.Property<string>("ReceiverCity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReceiverHomeAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenderCity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenderHomeAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
